version: "3.8"

services:
  app:
    build: .
    container_name: scheduler_service
    ports:
      - "${PORT_EXPOSE}:8008"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - MISFIRE_GRACE_TIME=${MISFIRE_GRACE_TIME}
      - TZ=Asia/Jakarta
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - scheduler_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    container_name: scheduler_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - scheduler_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  scheduler_network:
    driver: bridge

volumes:
  postgres_data:
